import express from "express";
import { createServer } from "http";
import { createRequire } from "module";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Repo docs/daily-reports.js: from dist/ go up to repo root then docs/
const reportsJsPath = path.resolve(__dirname, "..", "..", "docs", "daily-reports.js");
// Repo config/keywords.json (same file used by Python pipeline)
const keywordsJsonPath = path.resolve(__dirname, "..", "..", "config", "keywords.json");
// Repo reports/weekly (中英西班牙语周报)
const weeklyReportsDir = path.resolve(__dirname, "..", "..", "reports", "weekly");

function listWeeklyReports(): { id: string; date: string; title: string; summary: string; type: "weekly"; stats: { high: number; medium: number; low: number }; file: string; lang: string }[] {
  const results: { id: string; date: string; title: string; summary: string; type: "weekly"; stats: { high: number; medium: number; low: number }; file: string; lang: string }[] = [];
  if (!fs.existsSync(weeklyReportsDir)) return results;
  const files = fs.readdirSync(weeklyReportsDir).filter((f) => f.endsWith(".md"));
  const langLabels: Record<string, string> = { bilingual: "中英双语", zh: "中文", en: "English", es: "Español" };
  for (const file of files) {
    const match = file.match(/^weekly_(bilingual|zh|en|es)_(\d{4})_W(\d+)_(\d{4}-\d{2}-\d{2})\.md$/);
    if (!match) continue;
    const [, lang, year, week, date] = match;
    const langLabel = langLabels[lang] || lang;
    results.push({
      id: `weekly-${lang}-${year}-W${week}`,
      date,
      title: `${year} W${week} ${langLabel}`,
      summary: `周报 ${year} 第${week}周 (${langLabel})`,
      type: "weekly",
      stats: { high: 0, medium: 0, low: 0 },
      file,
      lang,
    });
  }
  results.sort((a, b) => b.date.localeCompare(a.date));
  return results;
}

async function startServer() {
  const app = express();
  const server = createServer(app);

  app.use(express.json({ limit: "512kb" }));

  // API: daily reports (data from docs/daily-reports.js, generated by daily_job_v2.py)
  app.get("/api/reports", (_req, res) => {
    try {
      const require = createRequire(import.meta.url);
      // 每次请求清除缓存，使本地更新 docs/daily-reports.js 后无需重启服务
      try {
        const resolved = require.resolve(reportsJsPath);
        if (require.cache[resolved]) delete require.cache[resolved];
      } catch {
        /* ignore */
      }
      const data = require(reportsJsPath);
      res.json({ dailyReports: data.dailyReports ?? [] });
    } catch (e) {
      console.warn("Failed to load docs/daily-reports.js:", e);
      res.status(500).json({ error: "Reports data unavailable", dailyReports: [] });
    }
  });

  // API: keywords config (read/write config/keywords.json, shared with Python pipeline)
  app.get("/api/keywords", (_req, res) => {
    try {
      const raw = fs.readFileSync(keywordsJsonPath, "utf-8");
      const data = JSON.parse(raw);
      res.json(data);
    } catch (e) {
      console.warn("Failed to load config/keywords.json:", e);
      res.status(500).json({ error: "Keywords config unavailable" });
    }
  });

  // API: weekly reports list (reports/weekly/*.md - 中英西班牙语周报)
  app.get("/api/weekly-reports", (_req, res) => {
    try {
      const list = listWeeklyReports();
      res.json({ weeklyReports: list });
    } catch (e) {
      console.warn("Failed to list reports/weekly:", e);
      res.status(500).json({ error: "Weekly reports unavailable", weeklyReports: [] });
    }
  });

  // API: single weekly report markdown (reports/weekly/{file})
  app.get("/api/weekly-report", (req, res) => {
    const file = req.query.file as string;
    if (!file || !/^weekly_(bilingual|zh|en|es)_\d{4}_W\d+_\d{4}-\d{2}-\d{2}\.md$/.test(file)) {
      return res.status(400).json({ error: "Invalid file parameter" });
    }
    try {
      const filePath = path.join(weeklyReportsDir, file);
      if (!fs.existsSync(filePath)) return res.status(404).json({ error: "File not found" });
      const content = fs.readFileSync(filePath, "utf-8");
      res.setHeader("Content-Type", "text/markdown; charset=utf-8");
      res.end(content);
    } catch (e) {
      console.warn("Failed to read weekly report:", e);
      res.status(500).json({ error: "Failed to read report" });
    }
  });

  app.put("/api/keywords", (req, res) => {
    const body = req.body;
    if (!body || typeof body !== "object") {
      return res.status(400).json({ error: "Invalid JSON body" });
    }
    if (!body.search_keywords || !body.competitors) {
      return res.status(400).json({ error: "Missing required keys: search_keywords, competitors" });
    }
    try {
      if (body.last_updated === undefined) {
        body.last_updated = new Date().toISOString().slice(0, 10);
      }
      const out = JSON.stringify(body, null, 2);
      fs.writeFileSync(keywordsJsonPath, out, "utf-8");
      res.json(body);
    } catch (e) {
      console.warn("Failed to write config/keywords.json:", e);
      res.status(500).json({ error: "Failed to save keywords config" });
    }
  });

  // Serve static files from dist/public in production
  const staticPath =
    process.env.NODE_ENV === "production"
      ? path.resolve(__dirname, "public")
      : path.resolve(__dirname, "..", "dist", "public");

  app.use(express.static(staticPath));

  // Handle client-side routing - serve index.html for all routes
  app.get("*", (_req, res) => {
    res.sendFile(path.join(staticPath, "index.html"));
  });

  const port = process.env.PORT || 3000;

  server.listen(port, () => {
    console.log(`Server running on http://localhost:${port}/`);
  });
}

startServer().catch(console.error);
