import { jsxLocPlugin } from "@builder.io/vite-plugin-jsx-loc";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";
import { defineConfig, type Plugin, type ViteDevServer } from "vite";
import { vitePluginManusRuntime } from "vite-plugin-manus-runtime";

// Path to repo's docs/daily-reports.js (data generated by daily_job_v2.py)
const REPORTS_JS = path.resolve(import.meta.dirname, "..", "docs", "daily-reports.js");
// Path to repo's config/keywords.json (shared with Python pipeline)
const KEYWORDS_JSON = path.resolve(import.meta.dirname, "..", "config", "keywords.json");
// Path to repo's reports/weekly (中英西班牙语周报)
const WEEKLY_REPORTS_DIR = path.resolve(import.meta.dirname, "..", "reports", "weekly");

function listWeeklyReports(): { id: string; date: string; title: string; summary: string; type: "weekly"; stats: { high: number; medium: number; low: number }; file: string; lang: string }[] {
  const results: { id: string; date: string; title: string; summary: string; type: "weekly"; stats: { high: number; medium: number; low: number }; file: string; lang: string }[] = [];
  if (!fs.existsSync(WEEKLY_REPORTS_DIR)) return results;
  const files = fs.readdirSync(WEEKLY_REPORTS_DIR).filter((f: string) => f.endsWith(".md"));
  const langLabels: Record<string, string> = { bilingual: "中英双语", zh: "中文", es: "Español" };
  for (const file of files) {
    const match = file.match(/^weekly_(bilingual|zh|es)_(\d{4})_W(\d+)_(\d{4}-\d{2}-\d{2})\.md$/);
    if (!match) continue;
    const [, lang, year, week, date] = match;
    const langLabel = langLabels[lang] || lang;
    results.push({
      id: `weekly-${lang}-${year}-W${week}`,
      date,
      title: `${year} W${week} ${langLabel}`,
      summary: `周报 ${year} 第${week}周 (${langLabel})`,
      type: "weekly",
      stats: { high: 0, medium: 0, low: 0 },
      file,
      lang,
    });
  }
  results.sort((a, b) => b.date.localeCompare(a.date));
  return results;
}

// =============================================================================
// /api/reports - serve daily reports from docs/daily-reports.js
// =============================================================================
function vitePluginReportsApi(): Plugin {
  return {
    name: "reports-api",
    configureServer(server: ViteDevServer) {
      server.middlewares.use("/api/reports", (_req, res, next) => {
        if ((_req as any).method !== "GET") return next();
        try {
          const require = createRequire(import.meta.url);
          // 每次请求清除缓存，使本地运行 daily_job_v2.py 更新 docs/daily-reports.js 后无需重启 dev server
          try {
            const resolved = require.resolve(REPORTS_JS);
            if (require.cache[resolved]) delete require.cache[resolved];
          } catch {
            /* ignore */
          }
          const data = require(REPORTS_JS);
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ dailyReports: data.dailyReports || [] }));
        } catch (e) {
          console.warn("[reports-api] Failed to load docs/daily-reports.js:", e);
          res.writeHead(500, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ error: "Reports data unavailable", dailyReports: [] }));
        }
      });
    },
  };
}

// =============================================================================
// /api/keywords - read/write config/keywords.json
// =============================================================================
function vitePluginKeywordsApi(): Plugin {
  return {
    name: "keywords-api",
    configureServer(server: ViteDevServer) {
      server.middlewares.use("/api/keywords", (req, res, next) => {
        const method = (req as any).method;
        if (method === "GET") {
          try {
            const raw = fs.readFileSync(KEYWORDS_JSON, "utf-8");
            const data = JSON.parse(raw);
            res.setHeader("Content-Type", "application/json");
            res.end(JSON.stringify(data));
          } catch (e) {
            console.warn("[keywords-api] Failed to load config/keywords.json:", e);
            res.writeHead(500, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: "Keywords config unavailable" }));
          }
          return;
        }
        if (method === "PUT") {
          let body = "";
          req.on("data", (chunk) => { body += chunk.toString(); });
          req.on("end", () => {
            try {
              const parsed = JSON.parse(body || "{}");
              if (!parsed.search_keywords || !parsed.competitors) {
                res.writeHead(400, { "Content-Type": "application/json" });
                res.end(JSON.stringify({ error: "Missing required keys: search_keywords, competitors" }));
                return;
              }
              if (parsed.last_updated === undefined) {
                parsed.last_updated = new Date().toISOString().slice(0, 10);
              }
              fs.writeFileSync(KEYWORDS_JSON, JSON.stringify(parsed, null, 2), "utf-8");
              res.setHeader("Content-Type", "application/json");
              res.end(JSON.stringify(parsed));
            } catch (e) {
              console.warn("[keywords-api] Failed to write config/keywords.json:", e);
              res.writeHead(500, { "Content-Type": "application/json" });
              res.end(JSON.stringify({ error: "Failed to save keywords config" }));
            }
          });
          return;
        }
        next();
      });
    },
  };
}

// =============================================================================
// /api/weekly-reports - list reports/weekly (中英西班牙语周报)
// =============================================================================
function vitePluginWeeklyReportsApi(): Plugin {
  return {
    name: "weekly-reports-api",
    configureServer(server: ViteDevServer) {
      server.middlewares.use("/api/weekly-reports", (_req, res, next) => {
        if ((_req as any).method !== "GET") return next();
        try {
          const list = listWeeklyReports();
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ weeklyReports: list }));
        } catch (e) {
          console.warn("[weekly-reports-api] Failed to list reports/weekly:", e);
          res.writeHead(500, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ error: "Weekly reports unavailable", weeklyReports: [] }));
        }
      });
      server.middlewares.use("/api/weekly-report", (req, res, next) => {
        if ((req as any).method !== "GET") return next();
        const file = (req as any).url?.split("?")[1]?.split("&").find((s: string) => s.startsWith("file="))?.slice(5);
        const decoded = file ? decodeURIComponent(file) : "";
        if (!decoded || !/^weekly_(bilingual|zh|es)_\d{4}_W\d+_\d{4}-\d{2}-\d{2}\.md$/.test(decoded)) {
          res.writeHead(400, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ error: "Invalid file parameter" }));
          return;
        }
        try {
          const filePath = path.join(WEEKLY_REPORTS_DIR, decoded);
          if (!fs.existsSync(filePath)) {
            res.writeHead(404, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: "File not found" }));
            return;
          }
          const content = fs.readFileSync(filePath, "utf-8");
          res.setHeader("Content-Type", "text/markdown; charset=utf-8");
          res.end(content);
        } catch (e) {
          console.warn("[weekly-reports-api] Failed to read weekly report:", e);
          res.writeHead(500, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ error: "Failed to read report" }));
        }
      });
    },
  };
}

// =============================================================================
// Manus Debug Collector - Vite Plugin
// Writes browser logs directly to files, trimmed when exceeding size limit
// =============================================================================

const PROJECT_ROOT = import.meta.dirname;
const LOG_DIR = path.join(PROJECT_ROOT, ".manus-logs");
const MAX_LOG_SIZE_BYTES = 1 * 1024 * 1024; // 1MB per log file
const TRIM_TARGET_BYTES = Math.floor(MAX_LOG_SIZE_BYTES * 0.6); // Trim to 60% to avoid constant re-trimming

type LogSource = "browserConsole" | "networkRequests" | "sessionReplay";

function ensureLogDir() {
  if (!fs.existsSync(LOG_DIR)) {
    fs.mkdirSync(LOG_DIR, { recursive: true });
  }
}

function trimLogFile(logPath: string, maxSize: number) {
  try {
    if (!fs.existsSync(logPath) || fs.statSync(logPath).size <= maxSize) {
      return;
    }

    const lines = fs.readFileSync(logPath, "utf-8").split("\n");
    const keptLines: string[] = [];
    let keptBytes = 0;

    // Keep newest lines (from end) that fit within 60% of maxSize
    const targetSize = TRIM_TARGET_BYTES;
    for (let i = lines.length - 1; i >= 0; i--) {
      const lineBytes = Buffer.byteLength(`${lines[i]}\n`, "utf-8");
      if (keptBytes + lineBytes > targetSize) break;
      keptLines.unshift(lines[i]);
      keptBytes += lineBytes;
    }

    fs.writeFileSync(logPath, keptLines.join("\n"), "utf-8");
  } catch {
    /* ignore trim errors */
  }
}

function writeToLogFile(source: LogSource, entries: unknown[]) {
  if (entries.length === 0) return;

  ensureLogDir();
  const logPath = path.join(LOG_DIR, `${source}.log`);

  // Format entries with timestamps
  const lines = entries.map((entry) => {
    const ts = new Date().toISOString();
    return `[${ts}] ${JSON.stringify(entry)}`;
  });

  // Append to log file
  fs.appendFileSync(logPath, `${lines.join("\n")}\n`, "utf-8");

  // Trim if exceeds max size
  trimLogFile(logPath, MAX_LOG_SIZE_BYTES);
}

/**
 * Vite plugin to collect browser debug logs
 * - POST /__manus__/logs: Browser sends logs, written directly to files
 * - Files: browserConsole.log, networkRequests.log, sessionReplay.log
 * - Auto-trimmed when exceeding 1MB (keeps newest entries)
 */
function vitePluginManusDebugCollector(): Plugin {
  return {
    name: "manus-debug-collector",

    transformIndexHtml(html) {
      if (process.env.NODE_ENV === "production") {
        return html;
      }
      return {
        html,
        tags: [
          {
            tag: "script",
            attrs: {
              src: "/__manus__/debug-collector.js",
              defer: true,
            },
            injectTo: "head",
          },
        ],
      };
    },

    configureServer(server: ViteDevServer) {
      // POST /__manus__/logs: Browser sends logs (written directly to files)
      server.middlewares.use("/__manus__/logs", (req, res, next) => {
        if (req.method !== "POST") {
          return next();
        }

        const handlePayload = (payload: any) => {
          // Write logs directly to files
          if (payload.consoleLogs?.length > 0) {
            writeToLogFile("browserConsole", payload.consoleLogs);
          }
          if (payload.networkRequests?.length > 0) {
            writeToLogFile("networkRequests", payload.networkRequests);
          }
          if (payload.sessionEvents?.length > 0) {
            writeToLogFile("sessionReplay", payload.sessionEvents);
          }

          res.writeHead(200, { "Content-Type": "application/json" });
          res.end(JSON.stringify({ success: true }));
        };

        const reqBody = (req as { body?: unknown }).body;
        if (reqBody && typeof reqBody === "object") {
          try {
            handlePayload(reqBody);
          } catch (e) {
            res.writeHead(400, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: false, error: String(e) }));
          }
          return;
        }

        let body = "";
        req.on("data", (chunk) => {
          body += chunk.toString();
        });

        req.on("end", () => {
          try {
            const payload = JSON.parse(body);
            handlePayload(payload);
          } catch (e) {
            res.writeHead(400, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ success: false, error: String(e) }));
          }
        });
      });
    },
  };
}

const plugins = [react(), tailwindcss(), jsxLocPlugin(), vitePluginReportsApi(), vitePluginKeywordsApi(), vitePluginWeeklyReportsApi(), vitePluginManusRuntime(), vitePluginManusDebugCollector()];

export default defineConfig({
  base: process.env.VITE_BASE_PATH ?? "/stablecoin-intel/",
  plugins,
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "client", "src"),
      "@shared": path.resolve(import.meta.dirname, "shared"),
      "@assets": path.resolve(import.meta.dirname, "attached_assets"),
    },
  },
  envDir: path.resolve(import.meta.dirname),
  root: path.resolve(import.meta.dirname, "client"),
  build: {
    outDir: path.resolve(import.meta.dirname, "dist/public"),
    emptyOutDir: true,
  },
  server: {
    port: 3000,
    strictPort: false, // Will find next available port if 3000 is busy
    host: true,
    allowedHosts: [
      ".manuspre.computer",
      ".manus.computer",
      ".manus-asia.computer",
      ".manuscomputer.ai",
      ".manusvm.computer",
      "localhost",
      "127.0.0.1",
    ],
    fs: {
      strict: true,
      deny: ["**/.*"],
    },
  },
});
